# Generated by Django 6.0.6 on 2026-07-01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("notices", "0003_inboxnotice_is_saved"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("slack", "Slack"),
                            ("kakao", "Kakao"),
                        ],
                        max_length=32,
                    ),
                ),
                ("config", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_channels",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AlertLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("error", models.TextField(blank=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "channel_id",
                    models.ForeignKey(
                        db_column="channel_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_logs",
                        to="alert.alertchannel",
                    ),
                ),
                (
                    "inbox_notice_id",
                    models.ForeignKey(
                        db_column="inbox_notice_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_logs",
                        to="notices.inboxnotice",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="alertchannel",
            index=models.Index(fields=["user_id", "type"], name="alert_alert_user_id_4791f0_idx"),
        ),
        migrations.AddIndex(
            model_name="alertlog",
            index=models.Index(fields=["status"], name="alert_alert_status_5799a5_idx"),
        ),
        migrations.AddIndex(
            model_name="alertlog",
            index=models.Index(fields=["sent_at"], name="alert_alert_sent_at_08c1e1_idx"),
        ),
    ]
