# Generated by Django 6.0.6 on 2026-07-03 06:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1024)),
                ('hash', models.CharField(blank=True, max_length=256)),
                ('title', models.CharField(max_length=256)),
                ('content', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('content_markdown', models.TextField(blank=True)),
                ('publisher', models.CharField(blank=True, max_length=128)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('deadline_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('source_id', models.ForeignKey(db_column='source_id', on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='sources.noticesource')),
            ],
        ),
        migrations.CreateModel(
            name='InboxNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevance_score', models.FloatField(default=0.0)),
                ('is_recommended', models.BooleanField(default=False)),
                ('matched_keywords', models.TextField(blank=True)),
                ('reason', models.TextField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_saved', models.BooleanField(default=False)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='inbox_notices', to=settings.AUTH_USER_MODEL)),
                ('notice_id', models.ForeignKey(db_column='notice_id', on_delete=django.db.models.deletion.CASCADE, related_name='inbox_entries', to='notices.notice')),
            ],
        ),
        migrations.AddConstraint(
            model_name='notice',
            constraint=models.UniqueConstraint(fields=('source_id', 'url'), name='unique_notice_source_url'),
        ),
        migrations.AddIndex(
            model_name='inboxnotice',
            index=models.Index(fields=['user_id', 'created_at'], name='notices_inb_user_id_a76d53_idx'),
        ),
        migrations.AddIndex(
            model_name='inboxnotice',
            index=models.Index(fields=['user_id', 'is_read'], name='notices_inb_user_id_7cbe4f_idx'),
        ),
        migrations.AddIndex(
            model_name='inboxnotice',
            index=models.Index(fields=['user_id', 'is_recommended'], name='notices_inb_user_id_5ea422_idx'),
        ),
        migrations.AddIndex(
            model_name='inboxnotice',
            index=models.Index(fields=['notified_at'], name='notices_inb_notifie_7a05ba_idx'),
        ),
        migrations.AddConstraint(
            model_name='inboxnotice',
            constraint=models.UniqueConstraint(fields=('user_id', 'notice_id'), name='unique_user_notice_inbox'),
        ),
    ]
