# Generated by Django 6.0.6 on 2026-07-01 05:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notices", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notice",
            name="deadline_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
