# Generated by Django 6.0.6 on 2026-07-03 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboxnotice',
            name='classified_by_llm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notice',
            name='enriched_by_llm',
            field=models.BooleanField(default=False),
        ),
    ]
