# Generated by Django 6.0.6 on 2026-07-01 05:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notices", "0002_notice_deadline_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="inboxnotice",
            name="is_saved",
            field=models.BooleanField(default=False),
        ),
    ]
