# Generated by Django 6.0.6 on 2026-07-02 14:06

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0003_inboxnotice_is_saved'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inboxnotice',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='inboxnotice',
            name='notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='inboxnotice',
            index=models.Index(fields=['user_id', 'created_at'], name='notices_inb_user_id_a76d53_idx'),
        ),
        migrations.AddIndex(
            model_name='inboxnotice',
            index=models.Index(fields=['user_id', 'is_read'], name='notices_inb_user_id_7cbe4f_idx'),
        ),
        migrations.AddIndex(
            model_name='inboxnotice',
            index=models.Index(fields=['notified_at'], name='notices_inb_notifie_7a05ba_idx'),
        ),
    ]
