# Generated by Django 6.0.6 on 2026-07-03 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0004_inboxnotice_created_at_inboxnotice_notified_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='content_markdown',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
