# Generated by Django 6.0.6 on 2026-07-03 05:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0005_notice_content_markdown_notice_summary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inboxnotice',
            name='is_recommended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='inboxnotice',
            index=models.Index(fields=['user_id', 'is_recommended'], name='notices_inb_user_id_5ea422_idx'),
        ),
    ]
