# Generated by Django 6.0.6 on 2026-06-30 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticesource',
            name='name',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
