# Generated by Django 6.0.6 on 2026-07-03 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticesource',
            name='extraction_profile',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='noticesource',
            name='last_extract_ok_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='noticesource',
            name='render',
            field=models.CharField(blank=True, default='http', max_length=16),
        ),
        migrations.AddField(
            model_name='noticesource',
            name='scraper_kind',
            field=models.CharField(blank=True, choices=[('', '미결정'), ('builtin', 'builtin'), ('rss', 'rss'), ('json_api', 'json_api'), ('heuristic', 'heuristic'), ('llm_profile', 'llm_profile')], default='', max_length=16),
        ),
    ]
