# Generated by Django 6.0.6 on 2026-07-03 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0002_alter_noticesource_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticesource',
            name='favicon_url',
            field=models.URLField(blank=True, max_length=1024),
        ),
    ]
