"""
Django settings for kkongal project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import environ
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

env = environ.Env(
    DEBUG=(bool, False)
)

environ.Env.read_env(
    env_file=BASE_DIR / '.env'
)

SECRET_KEY = env('SECRET_KEY')
DEBUG = env('DEBUG')

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'drf_spectacular',
    'rest_framework_simplejwt',
    "rest_framework_simplejwt.token_blacklist",
    'corsheaders',
    'account.apps.AccountConfig',
    'sources.apps.SourcesConfig',
    'notices.apps.NoticesConfig',
    'crawler.apps.CrawlerConfig',
    'alert.apps.AlertConfig',
    'ai.apps.AiConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "corsheaders.middleware.CorsMiddleware",
]

ROOT_URLCONF = 'kkongal.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'kkongal.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES' : (
        'rest_framework.permissions.AllowAny', 
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': (
        # 헤더(Bearer) + access_token 쿠키 모두 지원(프론트 쿠키 흐름 인증)
        'account.authentication.CookieJWTAuthentication',
    )
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Kkongal_API',
    'DESCRIPTION': '꽁알꽁알 API 명세서입니다.',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}

CORS_ALLOWED_ORIGINS= [
  'http://127.0.0.1:3000', 
  'http://localhost:3000',
]
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = (
    "accept",
    "authorization",
    "content-type",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
)

AUTH_USER_MODEL = 'account.User'

REST_USE_JWT = True 

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30), 
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1), 
    'ROTATE_REFRESH_TOKENS': True,  # 🔹 Refresh Token을 사용할 때마다 새 토큰 발급
    'BLACKLIST_AFTER_ROTATION': True,  # 🔹 이전 Refresh Token을 블랙리스트에 추가하여 재사용 방지
    'AUTH_HEADER_TYPES': ('Bearer',),  # 🔹 인증 헤더 타입을 "Bearer"로 설정
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),  # 🔹 Access Token 클래스를 지정
    'ACCESS_TOKEN': 'access_token',  # 🔹 Access Token의 이름 지정
    'REFRESH_TOKEN': 'refresh_token',  # 🔹 Refresh Token의 이름 지정
}

# ==========================================================================
# AI 공지 선별 (LLM) — OpenAI 호환 Chat Completions API
# --------------------------------------------------------------------------
# 기본값은 가성비가 가장 좋은 Google Gemini(무료 티어 존재)의 OpenAI 호환
# 엔드포인트를 가리킨다. OpenAI / DeepSeek / Groq / Together 등 OpenAI 호환
# 제공자로 자유롭게 교체 가능(LLM_BASE_URL, LLM_MODEL, LLM_API_KEY 만 변경).
# LLM_API_KEY 가 비어 있으면 키워드 기반 폴백으로 동작하여 오프라인/데모/테스트
# 환경에서도 안전하게 돌아간다.
# ==========================================================================
LLM_API_KEY = env('LLM_API_KEY', default='')
LLM_BASE_URL = env(
    'LLM_BASE_URL',
    default='https://generativelanguage.googleapis.com/v1beta/openai',
)
# gemini-2.5-flash-lite: Google 최저가 · 분류/라우팅 특화(가성비 최상). 무료 티어 존재.
LLM_MODEL = env('LLM_MODEL', default='gemini-2.5-flash-lite')
LLM_TIMEOUT_SECONDS = env.float('LLM_TIMEOUT_SECONDS', default=30.0)
LLM_MAX_CONTENT_CHARS = env.int('LLM_MAX_CONTENT_CHARS', default=2000)
# inbox 편입 및 알림 대상이 되는 최소 관련도(0.0~1.0)
LLM_RELEVANCE_THRESHOLD = env.float('LLM_RELEVANCE_THRESHOLD', default=0.5)

# ==========================================================================
# 이메일 알림 (SMTP) — Django 기본 메일 프레임워크 사용
# --------------------------------------------------------------------------
# 기본 backend는 콘솔 출력이라 자격 증명 없이도 데모/테스트가 동작한다.
# 실제 발송은 .env 에서 EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend
# 로 바꾸고 SMTP 자격 증명을 채우면 된다(예: Gmail 앱 비밀번호).
# ==========================================================================
EMAIL_BACKEND = env(
    'EMAIL_BACKEND',
    default='django.core.mail.backends.console.EmailBackend',
)
EMAIL_HOST = env('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = env.int('EMAIL_PORT', default=587)
EMAIL_USE_TLS = env.bool('EMAIL_USE_TLS', default=True)
# SMTP 연결이 멈춰도 요청이 무한 대기하지 않도록 타임아웃(초)을 둔다.
EMAIL_TIMEOUT = env.int('EMAIL_TIMEOUT', default=10)
EMAIL_HOST_USER = env('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = env(
    'DEFAULT_FROM_EMAIL',
    default='꽁알꽁알 <no-reply@kkongal.cloud>',
)

# ==========================================================================
# 슬랙 알림
# --------------------------------------------------------------------------
# 사용자는 각자 Incoming Webhook URL 을 alert_channels.config.webhook_url 에
# 등록한다. 아래 값은 등록된 채널이 없을 때 사용할 선택적 전역 폴백이다.
# ==========================================================================
SLACK_DEFAULT_WEBHOOK_URL = env('SLACK_DEFAULT_WEBHOOK_URL', default='')
SLACK_TIMEOUT_SECONDS = env.float('SLACK_TIMEOUT_SECONDS', default=10.0)

# 알림 메일/슬랙 메시지의 "대시보드에서 보기" 링크 등에 사용
FRONTEND_URL = env('FRONTEND_URL', default='http://localhost:3000')
